---
- hosts: all
  tasks:
    - debug: msg="{{ ansible_hostname }} {{ ansible_lsb.description }} ({{ ansible_distribution_release }})"
      when: ansible_os_family == "Debian"

- hosts: all
  roles:
    - vim
  tags:
    - vim

- hosts: all
  roles:
    - tmux
  tags:
    - tmux

- hosts: all
  roles:
    - bin
  tags:
    - bin

#    - role: awesome
#      when: ansible_os_family == "Debian"
#    - bash
#    - pyenv
#    - rbenv
