"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *General*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Mapleader
let mapleader = ","
let g:mapleader = ","

" Enable filetype plugins
filetype plugin on
filetype indent on


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Interface*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Line Number
set number

" Show cmd while typing
set showcmd

" Height of the command bar
set cmdheight=2

" Always show the status line
set laststatus=2

" Scroll margin
set scrolloff=7

" Turn on the Wild menu
set wildmenu

" Ignore compiled files
set wildignore=*.o,*~

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Searching Pattern
set ignorecase
set smartcase
set incsearch
set hlsearch

" Don't redraw while executing macros (good performance config)
set lazyredraw

" Show matching brackets when text indicator is over them
set showmatch
" How many tenths of a second to blink when matching brackets
set matchtime=2

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=

set timeoutlen=500

set completeopt=longest,menu


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *NOT SURE*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" A buffer becomes hidden when it is abandoned
set hidden

" Regular Expressions turn magic on
set magic


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Content Colors, Encoding, Fonts*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enable syntax highlighting
syntax enable

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Use Unix as the standard file type
set ffs=unix,dos,mac


if has("gui_running")
  set cursorcolumn
  set cursorline
  set guifont=Bitstream\ Vera\ Sans\ Mono\ 11
else
  " set cursorcolumn
  colorscheme desert
  set background=dark
endif

let g:indentLine_color_term = 239

set listchars=tab:▸- ",eol:¬
set list

set colorcolumn=80


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Files, backups and undo*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nobackup
set nowritebackup
set noswapfile


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Text, Tab and Indent*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Use spaces instead of tabs
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set softtabstop=4

" Linebreak on 500 characters
set linebreak
set textwidth=500

set autoindent
set smartindent
set wrap


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Moving around, tabs, windows and buffers*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Forbid arrow keys
map <LEFT> <Nop>
map <RIGHT> <Nop>
map <UP> <Nop>
map <DOWN> <Nop>

imap <LEFT> <Nop>
imap <RIGHT> <Nop>
imap <UP> <Nop>
imap <DOWN> <Nop>

" Treat long lines as break lines (useful when moving around in them)
map j gj
map k gk

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" emacs C-a, C-e
nmap <C-a> 0
imap <C-a> <ESC>0i
nmap <C-e> $
imap <C-e> <ESC>$a

map <F5> :tabprevious<cr>
map <F6> :tabnext<cr>

" Specify the behavior when switching between buffers
try
  set switchbuf=useopen,usetab,newtab
  set stal=2
catch
endtry

" Return to last edit position when opening files
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif
" Remember info about open buffers on close
set viminfo^=%


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Clipboard*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set clipboard^=unnamed

if $TMUX == ''
    set clipboard+=unnamed
endif


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Mappings*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" shift block
vmap << <gv
vmap >> >gv

nnoremap <space> za
nnoremap <CR> i<CR><ESC>

nmap <C-n> :NERDTreeToggle<cr>
nmap <F8> :! xdot %<.dot<cr><cr>

" Delete trailing white space on save, useful for Python and CoffeeScript ;)
func! DeleteTrailingWS()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc
autocmd BufWrite *.py :call DeleteTrailingWS()
autocmd BufWrite *.coffee :call DeleteTrailingWS()

" Disable highlight when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Helper functions*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
function! FcitxClose()
    let l:a = system("fcitx-remote -c")
endfunction
autocmd InsertLeave * call FcitxClose()


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Plugins*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
execute pathogen#infect()


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *vim markdown*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:vim_markdown_folding_disabled = 1


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Eclim*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:EclimFileTypeValidate = 0


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" *Python-Mode*
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:pymode_rope = 1
