---
- name: ensure .vim directory present
  file: path={{ item }}
        state=directory
        recurse=yes
  with_items:
    - ~/.vim/autoload
    - ~/.vim/bundle

- name: install pathogen.vim
  get_url: url=https://git.io/vl18W
           dest=~/.vim/autoload/pathogen.vim

- name: install bundles
  git: repo={{ item.repo }}
       dest=~/.vim/bundle/{{ item.name }}
  with_items:
    - name: ack.vim
      repo: https://github.com/mileszs/ack.vim.git
    - name: ctrlp.vim
      repo: https://github.com/kien/ctrlp.vim.git
    - name: indentLine
      repo: https://github.com/Yggdroot/indentLine.git
    - name: nerdtree
      repo: https://github.com/scrooloose/nerdtree.git
    - name: plantuml-syntax
      repo: https://github.com/aklt/plantuml-syntax.git
    - name: python-mode
      repo: https://github.com/klen/python-mode.git
    - name: syntastic
      repo: https://github.com/scrooloose/syntastic.git
    - name: tlib_vim
      repo: https://github.com/tomtom/tlib_vim.git
    - name: vim-addon-mw-utils
      repo: https://github.com/MarcWeber/vim-addon-mw-utils.git
    - name: vim-airline
      repo: https://github.com/bling/vim-airline.git
    - name: vim-easymotion
      repo: https://github.com/easymotion/vim-easymotion.git
    - name: vim-gitgutter
      repo: https://github.com/airblade/vim-gitgutter.git
    - name: vim-markdown
      repo: https://github.com/plasticboy/vim-markdown.git
    - name: vim-slumlord
      repo: https://github.com/scrooloose/vim-slumlord.git
    - name: vim-snipmate
      repo: https://github.com/garbas/vim-snipmate.git
    - name: vim-snippets
      repo: https://github.com/honza/vim-snippets.git
    - name: vim-surround
      repo: https://github.com/tpope/vim-surround.git
    - name: vim-tmux-focus-events
      repo: https://github.com/tmux-plugins/vim-tmux-focus-events.git
    - name: vim-go
      repo: https://github.com/fatih/vim-go.git
    - name: typescript-vim
      repo: https://github.com/leafgarland/typescript-vim.git

- name: configure vimrc
  template: src=vimrc
            dest=~/.vimrc
            backup=yes

- name: vim after ftplugin configurations
  copy:
    src: "{{ item }}"
    dest: ~/.vim/after/ftplugin/
    mode: 0644
  with_fileglob:
    - "after/ftplugin/*.vim"
