---
# tasks file for bin

- name: ensure ~/bin directory is ready
  file: path=~/bin
        state=directory
        recurse=yes

- name: ensure ve is installed
  get_url: url=https://raw.github.com/erning/ve/master/ve
           dest=~/bin/ve
           mode=0755

- name: copy bin files
  copy: src={{ item }}
        dest=~/bin/{{ item }}
        mode=0755
  with_items:
    - colordump
