---
# tasks file for bin

- name: ensure ~/bin directory is ready
  file: path=~/bin
        state=directory
        recurse=yes

- name: ensure ve/cht.sh is installed
  get_url:
    url: "{{ item.url }}"
    dest: "~/bin/{{ item.dst }}"
    mode: 0755
  with_items:
    - url: https://raw.github.com/erning/ve/master/ve
      dst: ve
    - url: https://cht.sh/:cht.sh
      dst: cht.sh

- name: copy bin files
  copy: src={{ item }}
        dest=~/bin/{{ item }}
        mode=0755
  with_items:
    - colordump
