---
- hosts: all
  tasks:
    - name: gather facts
      gather_facts:

- hosts: all
  roles:
    - { role: vim,  tags: ['vim'] }
    - { role: tmux, tags: ['tmux'] }
    - { role: bin,  tags: ['bin'] }
    - { role: homebrew, tags: ['homebrew'] }
  tags:
    - tools

#    - role: awesome
#      when: ansible_os_family == "Debian"
#    - bash
#    - pyenv
#    - rbenv
