---
- hosts: all
  gather_facts: no
  vars_prompt:
    - name: github_user
      prompt: GitHub user name, set authorized_key
      private: no
      confirm: true
  tasks:
    - apt:
        pkg:
          - fail2ban
          - mtr
          - dnsutils
          - iperf3
          - git
          - supervisor
          - tmux
          - socat
          - lsof
    - copy:
        content: |
          net.core.rmem_max=26214400
          net.core.wmem_max=26214400
          net.core.netdev_max_backlog=2048
          net.core.default_qdisc=fq
          net.ipv4.tcp_congestion_control=bbr
        dest: /etc/sysctl.d/99-network.conf
    - authorized_key:
        user: root
        state: present
        key: 'https://github.com/{{ github_user|quote }}.keys'
    - user:
        name: root
        password_lock: true

- hosts: all
  gather_facts: no
  roles:
    - { role: tmux }
