---
- hosts: all
  gather_facts: no
  tasks:
    - apt:
        pkg:
          - fail2ban
          - mtr
          - dnsutils
          - iperf3
          - git
          - supervisor
    - copy:
        content: |
          net.core.rmem_max=26214400
          net.core.wmem_max=26214400
          net.core.netdev_max_backlog=2048
          net.core.default_qdisc=fq
          net.ipv4.tcp_congestion_control=bbr
        dest: /etc/sysctl.d/99-network.conf
